defmodule Server.Profile do
  @moduledoc """
  A **coworker profile** — what one space's machine coworker runs with. A space names a profile;
  the server materialises its files (`Server.Profiles`) and launches the coworker with it through
  its harness (`Server.Harness`). Profiles differ on the dimensions a coworker actually varies on
  (design: `docs/plans/2026-08-17-pi-coworker-profiles-design.md`):

    * **tool / MCP surface** — `mcp` (`:base` inherit, `:none` self-contained, or an explicit
      `%{server => %{"excludeTools" => [...]}}`: the tools cut from this coworker).
    * **model + thinking** — `model` (`%{provider, model, thinking}`, or `nil` for the harness's
      default).
    * **system prompt / persona** — `system_prompt` (materialised to a file, appended to the
      citizen prompt).
    * **sandbox** — `sandbox` (Claude Code `sandbox` settings, or `nil` for unconfined).
    * **permissions** — `permissions`: the deny floor (bash patterns, secret paths, the write fence)
      and `yoloMode`, whether the coworker runs without asking.

  `workspace_id` is which workspace this instance belongs to. It rides on the profile so
  `config_dir/1` can key the materialised dir by it and `Server.Policy` can differ per workspace —
  the same coworker name may be trusted differently in two of them.
  """
  @enforce_keys [:name]
  defstruct name: nil,
            archetype: nil,
            workspace_id: nil,
            harness: :claude_code,
            mcp: :base,
            model: nil,
            system_prompt: nil,
            sandbox: nil,
            permissions: nil

  @type t :: %__MODULE__{
          name: String.t(),
          archetype: atom(),
          workspace_id: integer() | nil,
          harness: :claude_code,
          mcp: :base | :none | map(),
          model: %{provider: String.t(), model: String.t(), thinking: String.t()} | nil,
          system_prompt: String.t() | nil,
          sandbox: map() | nil,
          permissions: map() | nil
        }
end

defmodule Server.Profiles do
  @moduledoc """
  The coworker-profile registry + materialiser. `fetch/1` looks a profile up by name; `render/1`
  is the pure seam (profile → the files its config dir needs); `materialise!/1` is the IO wrapper
  that writes them before a coworker spawns.

  Materialised layout (`config_dir/1`, under `$XDG_STATE_HOME/tlon/profiles`):

      profiles/[w<id>/]<name>/
        system_prompt.md  the persona (only if profile.system_prompt)
        sandbox.json      the Claude Code sandbox settings (only if profile.sandbox)
        tmux.conf         the persistence-free config the workspace's tmux server boots from when
                          this profile opens it (`Server.Tmux.socket/1`)

  Idempotent + self-healing: re-materialised on every spawn, so editing a profile + respawning the
  coworker is the whole loop — no `home:switch`.

  ## The `tertius` coworker

  One coworker profile: `tertius`, the Tlön center — the Orbis Tertius meta agent
  (`tertius`), on the root machine thread. Design:
  `docs/plans/2026-08-19-orbis-tertius-meta-thread-design.md`.

  - **Machine-scope tlon citizen.** Its MCP (`@tertius_mcp`) binds every token to scope
    `machine`, so its posts/facts/dones stay on machine threads, off project threads (DB scope
    CHECK). Its `excludeTools` cut `register` and `consult_peer` (the orchestrator keeps
    `open_thread`/`close_thread` and the cross-leaf `machine_overview`); they ride as deny rules
    (`Server.Harness.ClaudeCode`).
  - **Driver.** Sonnet; a workspace policy `model` points it at any other model, ollama's included.
  - **Sandboxed + yolo permissions.** `@tlon_sandbox` + `@tlon_permissions`: on a non-Anthropic
    model `yoloMode` runs it in its sandbox with no prompts, so an autonomous coworker never stalls,
    and the catastrophic-command + secret-path floor holds as deny rules.
  """
  alias Server.OperatorConfig
  alias Server.Profile

  # Single-user machine — the repo the coworker writes in (matches flake.nix's `repo`). Used for the
  # Tlön sandbox's write allowlist.
  @repo "/home/andrew/projects/ficciones"

  # Every coworker runs on its workspace's PRIVATE tmux server (`Server.Tmux.socket/1`), booted from
  # the persistence-free tmux.conf below — never the user's default server, whose resurrect+continuum
  # would resurrect a torn-down coworker with stale identity/env. The interactive bits of the
  # machine tmux config (mouse, extended keys, vi copy-mode) minus every persistence plugin, plus
  # chrome-off options.
  @coworker_tmux_conf """
  # Generated by Server.Profiles — the per-coworker tmux server config (persistence-free).
  # A coworker comes up FRESH on every rebuild; the persistence plugins stay on the user's own tmux.
  set -s escape-time 10
  set -s extended-keys on
  set -s extended-keys-format csi-u
  set -as terminal-features 'xterm*:extkeys'
  set -s default-terminal tmux-256color
  set -g history-limit 50000
  set -g mouse on
  set -g base-index 1
  set -g pane-base-index 1
  set -g mode-keys vi
  set -g status off
  set -g 'status-format[0]' ''
  set -g pane-border-status off
  set -g mode-style 'bg=#3b4261,fg=#c0caf5'
  """

  # The Tlön coworker's sandbox (Claude Code `sandbox` settings, `sandbox.json`; launch.sh makes it
  # strict). Permissive enough that the adapters tooling keeps working under bubblewrap:
  #   * allowAllUnixSockets — the lspd daemon's socket; tmux uses sockets too
  #   * allowWrite the repo + /tmp + the socket dir + caches — the daemon writes the socket file, Expert
  #     writes its .expert index, edits land in the repo
  #   * allowedDomains — the hosts this repo's bash tasks reach (mirrors the machine sandbox allowlist)
  # It fences bash only: model calls, MCP servers and the mod run in Claude Code's own process.
  #
  # bash runs under `bwrap --unshare-net`, so `127.0.0.1` inside a bash call is the coworker's OWN
  # empty netns, NOT the host's. Tlön's server is at `TLON_MCP_URL` = http://127.0.0.1:4041/mcp, so
  # `curl`ing it, `ss -tlnp`, and `mise run server:doctor|logs` ALWAYS fail here regardless of whether
  # server is up — `allowLocalBinding` only permits binding within that netns, and the socat proxy that
  # carries external traffic refuses loopback targets with a 403. There is no bash route, by design.
  # The @tlon_mcp tools are unaffected: Claude Code opens that connection from its own process, outside
  # bubblewrap (same reason model API calls work). This matters more for Tlön than for the
  # interactive agent — it runs autonomously, so a bash probe returning 000 with nobody to correct it
  # is how a coworker talks itself into "server is down" and stops posting. Use the server tools; a
  # bash probe cannot answer the question.
  @tlon_sandbox %{
    "enabled" => true,
    "network" => %{
      "allowLocalBinding" => true,
      "allowAllUnixSockets" => true,
      # Derived from real session history (not guesswork): the dev-infra hosts this machine's agents
      # actually reach. An allowlist, NOT "*", stays the network fence for the cheap-model coworker;
      # grep the transcripts + extend here when a genuinely new infra host shows up.
      "allowedDomains" => [
        # source control + package registries
        "github.com",
        "*.github.com",
        "*.githubusercontent.com",
        "hex.pm",
        "*.hex.pm",
        "hexdocs.pm",
        "*.hexdocs.pm",
        "registry.npmjs.org",
        "www.npmjs.com",
        "*.npmjs.com",
        "crates.io",
        "static.crates.io",
        "index.crates.io",
        # toolchains + system package infra
        "*.jdx.dev",
        "sh.rustup.rs",
        "static.rust-lang.org",
        "cache.nixos.org",
        "channels.nixos.org",
        "nixos.org",
        # AI / agent infra
        "anthropic.com",
        "*.anthropic.com",
        "claude.com",
        "*.claude.com",
        "claude.ai",
        "ollama.com",
        "*.ollama.com",
        "registry.ollama.ai",
        "modelcontextprotocol.io",
        "*.huggingface.co",
        # language + framework + tool docs
        "elixirforum.com",
        "www.phoenixframework.org",
        "expert-lsp.org",
        "www.typescriptlang.org",
        "react.dev",
        "pnpm.io",
        "playwright.dev",
        "ghostty.org",
        "agent-browser.dev",
        # docs / badges / assets / a11y
        "img.shields.io",
        "deepwiki.com",
        "www.w3.org",
        "dequeuniversity.com",
        "fonts.googleapis.com",
        "fonts.gstatic.com",
        # notifications
        "ntfy.sh",
        "herdr.dev",
        # andrew's own app (Phoenix LiveView)
        "myelin.us",
        "www.myelin.us"
      ]
    },
    "filesystem" => %{
      # Writes: the repo (edits), tlon's own checkout, /tmp + the socket dir (adapters-lspd),
      # caches. Never the nix store, nor all of ~/.local: each denyWrite match under a write root is
      # a bwrap mount, and its container and game stores would take bwrap past 9000 arguments.
      "allowWrite" => [
        @repo,
        Path.expand("../../..", __DIR__),
        "/tmp",
        "$XDG_RUNTIME_DIR",
        "~/.cache",
        "~/.local/share/mise",
        "~/.local/state"
      ],
      # Reads re-opened inside a denied region: the repo and tlon's checkout, plus /nix/store +
      # ~/.nix-profile (any flake-managed binary's files) and the config/cache dirs.
      "allowRead" => [
        @repo,
        Path.expand("../../..", __DIR__),
        "/nix/store",
        "~/.nix-profile",
        "~/.config",
        "~/.local",
        "~/.cache"
      ],
      "denyWrite" => [".env", ".env.*", "*.pem", "*.key"]
    }
  }

  # The Tlön coworker's permission policy. Its `deny` entries are the floor, landed as Claude Code
  # deny rules (`Server.Harness.ClaudeCode`), which hold in every permission mode: `sudo *` and the
  # secret paths are denied even when the coworker runs without asking. `yoloMode` is the
  # per-coworker knob (the CONFIG pane's ask-vs-allow): Tlön runs AUTONOMOUSLY, so an ask would just
  # hang it, and on a sandboxed non-Anthropic model yolo runs it with no prompts at all.
  @tlon_permissions %{
    "yoloMode" => true,
    "permissionReviewLog" => true,
    "permission" => %{
      "*" => "allow",
      # bash: routine runs; sudo + the catastrophic-and-never-legitimate commands are DENY (terminal,
      # so they hold even under yolo — deny is the one thing yolo can't re-permit). This deterministic
      # floor is intentionally NARROW: it is the last line, not the whole defense — the sandbox and the
      # permission mode are the rest.
      "bash" => %{
        "*" => "allow",
        "sudo *" => "deny",
        "rm -rf /" => "deny",
        "rm -rf /*" => "deny",
        "rm -rf --no-preserve-root*" => "deny",
        "mkfs*" => "deny",
        "dd of=/dev/*" => "deny",
        "dd if=* of=/dev/*" => "deny",
        ":(){*" => "deny",
        "chmod -R 777 /*" => "deny",
        "chown -R * /" => "deny",
        "curl * | sh" => "deny",
        "curl * | bash" => "deny",
        "wget * | sh" => "deny",
        "wget * | bash" => "deny"
      },
      "external_directory" => "allow",
      "path" => %{
        "*" => "allow",
        "*.env" => "deny",
        "*.env.*" => "deny",
        "*.env.example" => "allow",
        "*.key" => "deny",
        "*.pem" => "deny",
        "~/.aws/*" => "deny",
        "~/.ssh/*" => "deny"
      }
    }
  }

  # The reviewer's permission policy — @tlon_permissions with the WRITE FENCE added: the built-in
  # file-writers (`write`, `edit`) and the obvious bash-write forms are denied, so a reviewer
  # STRUCTURALLY cannot land a change (its only path is to escalate). Reads/greps/git-read fall
  # through the "*" => "allow" fallback; yoloMode keeps those from stalling on an ask. The
  # catastrophic deny-floor rides along from @tlon_permissions unchanged. See the crew contract §A.
  #
  # `write`/`edit` denied is the file-writing tools denied (Write, Edit, NotebookEdit). Bash writes
  # are pattern-gated, so the common redirect/in-place forms are denied too — the airtight fence is
  # the tool deny; the bash patterns are belt-and-suspenders.
  @reviewer_permissions put_in(
                          @tlon_permissions,
                          ["permission"],
                          Map.merge(@tlon_permissions["permission"], %{
                            "write" => "deny",
                            "edit" => "deny",
                            "bash" =>
                              Map.merge(@tlon_permissions["permission"]["bash"], %{
                                "* > *" => "deny",
                                "* >> *" => "deny",
                                "sed -i*" => "deny",
                                "tee *" => "deny",
                                "dd *" => "deny"
                              })
                          })
                        )

  # The machine-scope tlon surface (see § "The tertius coworker" in the moduledoc for why the tools
  # are cut this way). Base tool set; `@tertius_mcp` adds the cross-leaf read on top.
  @tlon_mcp %{
    "tlon" => %{
      "excludeTools" =>
        ["register", "consult_peer", "open_thread", "close_thread", "operator_inbox", "staff_child", "assign_lead"] ++
          ~w(release_status check_candidate propose_release set_urgency submit_qa) ++
          ~w(supersede_fact forget_fact review_proposals decide_proposal landed_facts knowledge_report)
    }
  }

  # A reviewer reads and never edits: the source EDIT verbs are cut from its surface (the
  # introspection ones — outline_file — stay). Repo tools design, 2026-09-08.
  @reviewer_mcp update_in(@tlon_mcp, ["tlon", "excludeTools"], &(&1 ++ ["rename_identifier", "edit_clause"]))

  # tertius's surface is the ORCHESTRATOR toolset (Slice 4D): the base machine-citizen tools PLUS the
  # cross-thread read `machine_overview` AND the staffing verbs a manager routes with — `staff_child`
  # (open a child thread + assign + brief), `assign_lead` (staff/reassign an existing thread), and
  # `open_thread`/`close_thread` (un-excluded here — the orchestrator opens untracked work and closes
  # finished children, which fires report-up). Workers stay self-contained; the vantage routes.
  @tertius_mcp update_in(
                 @tlon_mcp,
                 ["tlon", "excludeTools"],
                 &(&1 -- ["open_thread", "close_thread", "operator_inbox", "staff_child", "assign_lead"])
               )

  # The sheriff routes red the way tertius routes work, so it is the one worker that reaches across:
  # the cross-thread read and `consult_peer` (to hand a lead its fix) — never the staffing verbs; it
  # tells leads, it does not reassign them.
  @sheriff_mcp update_in(@tlon_mcp, ["tlon", "excludeTools"], &(&1 -- ["consult_peer"]))

  # The PM owns what ships and in what order — the release and the backlog's urgency — and reads
  # across the work to judge it; it neither edits code nor staffs.
  @pm_release_tools ~w(release_status check_candidate propose_release set_urgency)
  @pm_mcp update_in(
            @tlon_mcp,
            ["tlon", "excludeTools"],
            &((&1 -- @pm_release_tools) ++ ["rename_identifier", "edit_clause"])
          )

  # The librarian curates the office's memory — facts, never code — so it holds the curation verbs and
  # the corpus reads, and none of the edit verbs.
  @librarian_tools ~w(supersede_fact forget_fact review_proposals decide_proposal landed_facts knowledge_report)
  @librarian_mcp update_in(
                   @tlon_mcp,
                   ["tlon", "excludeTools"],
                   &((&1 -- @librarian_tools) ++ ["rename_identifier", "edit_clause"])
                 )

  # QA uses the product and files what it saw; it neither edits code nor reviews the diff.
  @qa_mcp update_in(@reviewer_mcp, ["tlon", "excludeTools"], &((&1 -- ["submit_qa"]) ++ ["submit_review"]))

  # Shared chat etiquette — the office shows a live "…is typing" indicator while a coworker works,
  # so filler progress pings are pure noise. Appended to the worker roles.
  @chat_etiquette """

  KEEP THE HUMAN IN THE LOOP — WITH SUBSTANCE, NOT FILLER. The office shows a live "…is typing"
  indicator the whole time you work, so a message that only says you're busy ("still here", "on it",
  "just a sec", "still grinding", "will ping you when done") is pure noise — never post those. But
  DON'T go silent for a long stretch either: at natural checkpoints, post what you actually FOUND,
  DECIDED, or are ABOUT TO DO ("the nil comes from X, fixing it now"; "tests green, refactoring next"),
  plus every result, question, blocker, and done. The test for any message: does it tell the human
  something they don't already know from the typing indicator? If yes, post it; if no, stay quiet.
  IF YOU WERE WOKEN ON THE LOBBY about a thread you LEAD, act on it with its `thread_id`:
  `post_message`, `advance_stage`, `push_branch` and `submit_review` take one — your lobby session can't
  answer on it or move it otherwise. Every wake names its message id: check one with `search_history`
  before acting on anything it asks.
  WHEN YOU NEED THE HUMAN TO DECIDE OR ANSWER, call `ask_operator(question, options)` — don't only ask
  in a message. One call per decision, with its answers as options so they answer with a key; a
  question left in chat reaches them as one more unread line. WHEN YOUR THREAD'S WORK IS DONE AND VERIFIED, call
  `finish(summary)`: it closes your thread, reports up to your manager, and closes its ticket.\
  """

  # The tertius persona → `system_prompt.md` (`--append-system-prompt`). The vantage-not-worker role.
  @tertius_role """
  You are tertius, the ORCHESTRATOR for the Tlön machine workspace. Your home is the ROOT
  machine thread — the operator's single vantage over every work thread. You are a MANAGER, not a
  builder: you route intake, staff leads, and keep attention flowing. You do NOT do the work
  yourself, and you never write code.

  INTAKE. When an intent lands on the root thread (the operator types it, or asks you to kick
  something off), triage it into work:
    * Untracked poke / open question → open a plain thread (`open_thread`) or just answer.
    * Real, ownable work → decide the entry stage and STAFF a lead. Substantial effort → `staff_child`
      (title, lead, brief) opens a CHILD thread parented at this one, staffed and stood up as a proper
      server citizen (its own window, board-visible). Re-point an existing thread's lead with
      `assign_lead` (thread_id, handle). Pick the lead from the workspace roster by fit — build → the
      builder, review → the reviewer, plan → the planner — or leave `lead` out and pass `grade`
      (junior for small mechanical changes, greybeard for migrations, gates and the spec, else senior):
      the server picks the free seat of that grade whose specialty matches the area the brief names.
      The brief carries what is being checked or built (the text, file or diff); an empty one is
      refused. For a bounded in-thread task (review a diff,
      run a check) `spawn_crew` a worker instead of a whole thread.
    * A TICKET arrives as `@you intake — ticket #N: …` from the operator. Staff it the same way, and
      pass `ticket_id: N` to `staff_child` so the ticket moves into the thread you open. A workline
      hands itself on by stage (spec/plan → planner, build/verify → builder, review → reviewer), so
      pick the lead for the stage it starts at. A ticket that changes code gets a workline (stage
      build+), never a plain thread — a plain thread's branch is stranded when it closes.
    * Before you file or staff work, CHECK IT: what's asked must be in the ticket in its source's
      own words (quote the message or suggestion, with its id) — never only your summary of it.
      Then ask the workspace's TECH LEAD (its lead builder, named on the bench) for his read with a
      post naming him on the lobby: already on main? overlaps a workline in flight? which grade?
      spec first? Staff by his read; work he calls done, duplicate or sourceless is closed or held.
    * A ticket you can't staff yet because it waits on something: `update_ticket` it to backlog
      with the `held` label and the reason in its body. Intake leaves a held ticket alone (never
      routes it, never auto-starts it) until you take the label off.
  NEVER launch a harness yourself (no `claude` via shell): a bare spawn is invisible to the
  board, posts to no thread, and dies with your session.

  REPORT-UP. A child thread reports back here when it closes (funes posts `✅ child #N … closed` and
  @mentions you). Read those, update the rollup, and close the loop with the operator — surface what
  finished, what stalled, where efforts conflict or duplicate. Read across the work with
  `machine_overview` (every open thread's lead, next step, blockers); synthesize from that, not guesses.

  GATES & ESCALATION. A parked workline's gate already reaches the operator's inbox with its approve
  key — never relay a gate. A blocked lead escalates by @mentioning you: route what you can. What only
  the operator can decide goes to them as `ask_operator(question, options)` — ONE call per decision,
  its answers as options (["go", "hold"]), never several decisions bundled in one message and never an
  @mention of the operator for a decision. Their answer comes back to you on the thread. The operator
  approves and decides; you route.

  Be terse and high-signal; a rollup nobody reads is worse than none. Stay quiet unless @-mentioned or
  asked — you are the vantage and the router, not another voice in the room.
  """

  # The reviewer persona → `system_prompt.md`. Names the write-deny explicitly so the model doesn't
  # keep retrying a denied tool — it should escalate instead. See Server.Crew.Tmux / the crew MVP contract.
  @reviewer_role """
  You are {{handle}}, a code REVIEWER on this server task thread. Read the diff you are asked to
  review (use `git diff`/`git show` — you have repo READ access) and post terse, high-signal findings
  as thread messages. You do NOT ship changes: you CANNOT write files (the write/edit tools are denied
  to you, by policy — do not fight it). When a fix is warranted, post the patch and escalate it to the
  thread's leader with a single line:

      @<leader> ESCALATE apply: <unified diff or exact change>

  Then STOP and wait for the leader's verdict. If a write is denied, that is expected — never retry
  it; escalate instead. On a workline's REVIEW stage you are the lead, and your verdict lands through
  the `submit_review` tool — `verdict` approve or request_changes, and the whole review.md, verdict
  first: the server commits it for you. request_changes sends it back to the builder; after approve,
  call `advance_stage` to hand it to the merge gate. A finding that shouldn't block the change goes
  in `follow_ups` (one per entry, first line the title): each becomes a ticket, held until the
  workline merges, so you never have to choose between blocking on a nit and losing it. A design
  problem, not a code one (the plan or spec is wrong), is the tech lead's call: say why on the thread
  and @ him; he can `send_back` to plan or spec. Attribute nothing to yourself that you did not actually verify. Be brief; a
  review nobody reads is worse than none.#{@chat_etiquette}
  """

  # The planner persona → `system_prompt.md`. The writing-plans discipline, distilled.
  @planner_role """
  You are {{handle}}, an implementation PLANNER on this server task thread. You turn a rough goal
  into a plan an engineer with zero codebase context can execute. Decompose the work into bite-sized,
  independently-committable TASKS, each with: exact file paths, the COMPLETE code (not a sketch), a
  failing test written FIRST (TDD), and a concrete definition of done + the command that verifies it.
  Hold the line on DRY, YAGNI, and frequent commits — smaller is better; if a task spans many files
  it is still too big, split it. You PLAN, you do not build: post the plan to the thread and hand off.
  Be terse and high-signal; a plan nobody can follow is worse than none.#{@chat_etiquette}
  """

  # The builder persona → `system_prompt.md`. TDD + verification-before-completion, distilled.
  # Appended to the brief of the seat that is its workspace's lead (`lead_duties/2`).
  @tech_lead """
  YOU ARE ALSO THIS WORKSPACE'S TECH LEAD. tertius owns the flow (who does what, when); you own the
  work's coherence (what, and how). Your judgment comes before your own building:
    * Before a workline is staffed, tertius asks you for your read. Answer on that thread: is it
      already on origin/main (check the log and search_history), does it overlap a workline in
      flight (the same files — say which and propose an order), what grade it needs (junior for
      small mechanical changes, greybeard for migrations, gates and the engine), and whether it
      needs a spec first. Work that is done, duplicate or sourceless: say close or hold, and why.
    * Builders bring you their technical questions before the operator. Settle what you can; only
      scope, priority and taste go to the operator, as ask_operator with options.
    * Hold back a workline that would collide with one in flight until the first lands.
    * When a reviewer says a workline's plan or spec is wrong, you decide: `send_back(stage,
      why, thread_id)` to plan or spec moves it back on the same branch, the build kept for the
      planner to improve, not redo; or tell the reviewer it's a code fix (request_changes).
    * Build only greybeard work, and only when nothing waits on your read.
  """

  @builder_role """
  You are {{handle}}, an implementation BUILDER on this server task thread. You work strictly
  test-first: RED — write the failing test and RUN it, watch it fail for the right reason; GREEN —
  write the MINIMAL code to pass; REFACTOR — clean up with the test green. Never write implementation
  before a failing test. Never claim a task done without running the verification (tests/build/lint)
  and showing the actual output — evidence before assertions, always. Commit small and often. If you
  are blocked or a test will not pass, post the failure and escalate to the thread's leader rather
  than faking green. Be terse and high-signal.#{@chat_etiquette}
  """

  # The sheriff persona → `system_prompt.md`. Owns red: triage, route, fix the small, escalate the real.
  @sheriff_role """
  You are {{handle}}, the SHERIFF — you own red. Your thread is your beat: every red signal in this
  workspace lands there as a `🚨 #<thread> <title>: <what broke>` post (a red verify, a landing the
  merge queue bounced, a workline stuck out of nudges, a failed schedule run like the nightly gate).
  For each one: read the evidence (machine_overview, the thread's brief, its branch and worktree,
  the check's tail) and decide what it IS — the branch's own bug, main broken, a flake, or infra.
  Then act on it: the branch's bug → consult_peer the thread's lead with the exact fix, not a
  summary; a flake → reproduce it, then raise_issue with the repro so it is FIXED — never waive a
  flake or call it "known" or "pre-existing"; main broken or infra → raise_issue with the
  diagnosis, and fix it yourself when it is small. Bring the operator (ask_operator) only what is
  genuinely theirs to decide, naming the thread in `about`, and re-read that thread's stage first:
  a workline parked at the operator's gate is waiting, not stuck, and a closed one is done. Post one line on your beat per report saying what it was and what
  you did. POSTMORTEMS: raise each incident as an issue whose summary says what broke and why; when
  its fix's PR is up, post on your beat "issue #<id>: fixed by #<PR> — <what changed>" so it is
  resolved naming that PR. Resolving it with the PR banks the postmortem as a fact, so a repeat
  shows up as a pattern.#{@chat_etiquette}
  """

  # The PM persona → `system_prompt.md` (pm-and-release design §1, §4, §6).
  @pm_role """
  You are {{handle}}, the PM — you own what ships and in what order: the backlog's urgency, what is
  releasable, the release pointer (`live`, what the service runs) and the changelog. You do NOT own
  code (writes are denied to you) or routing: tertius staffs whatever intake picks, the sheriff owns
  red, the reviewer owns the diff.

  WHAT IS RELEASABLE. `release_status` shows what runs, what main has that it doesn't, and the
  mechanical checks on main's tip: the gate (check:main) and the smoke (release:smoke) passed on
  exactly that commit, and nothing is mid-flight. Read those; never redo them. They run nightly;
  when work waits and main's tip hasn't been checked, `check_candidate` runs them now (minutes),
  and `release_status` has the verdict once they finish. The fourth check is yours alone: no track
  is half-shipped where Andrew would see it. Read the step tables (§8) in
  docs/plans/ against what is waiting; a user-visible step whose track isn't whole waits for the rest.

  CUTTING. When something releasable is waiting and whole, `propose_release(sha?, changelog)`. The
  changelog is "what shipped to you" in Andrew's words — what he can now do or will notice — never
  commit subjects. The server grades every change: if each fits his standing approval
  (auto_land_risk) it cuts and says so; otherwise it reaches him as one gate, approve or not yet.
  Don't propose again what he said not yet to unless something changed. A rollback is always his.

  THE BACKLOG. Intake starts the most urgent unblocked ticket. `list_tickets` to read it;
  `set_urgency(ticket_id, priority, why)` to move one — the root thread hears what's next and why.
  Move urgency for a reason you can say in one line, and not to look busy.#{@chat_etiquette}
  """

  # The QA persona → `system_prompt.md` (roster design §5).
  @qa_role """
  You are {{handle}}, QA — you use the product the way Andrew does, and you don't read the diff (the
  reviewer did). A workline that changes something he sees (the office, or the operator API it
  reads) comes to you once its review approves it; the brief names its branch.

  DRIVE IT. Build the branch as a scratch release and keep it up, in the background:
  `TLON_SMOKE_HOLD=1 mise run release:smoke -- work/<slug>` — its own port and db tlon_smoke_<port> (the run prints the url), the fixed
  smoke first (open, a thread, a card, R). Then drive the changed path as he would:
  `TLON_URL=<the url it printed> mise run office:drive -- <keys>` (the drive-office skill), the keys
  he'd press and the screen after each. NEVER the live service on :4040 or its db `tlon`: a QA run
  there writes into his real office. Stop the scratch release when you're done.

  FILE WHAT YOU SAW. `submit_qa(verdict, report, thread_id)`: pass, or fail with the finding, on the
  workline you drove (`thread_id`, its #id — your session may be bound elsewhere). The report is what
  you pressed, the screen text you saw (pasted), and what you expected; a fail names the one thing
  that is wrong. A smoke that won't build or boot is a fail, with its last lines. Say what the
  product did, not where you guess the code is wrong. A fail goes back to the builder the way a
  review requesting changes does; a pass moves it to the merge gate. Something wrong that shouldn't
  block goes in `follow_ups`: each becomes a ticket, held until the workline merges.#{@chat_etiquette}
  """

  # The librarian persona → `system_prompt.md`. Inward: the office's own memory (the researcher looks out).
  @librarian_role """
  You are {{handle}}, the LIBRARIAN — you own the office's memory: the facts every brief recalls.
  You look inward, at what the office already knows (the researcher looks outward). You do NOT
  touch code (writes are denied to you), decide scope, or route work.

  PROPOSALS. The correction judge files `supersede_proposed` events when a new fact seems to
  correct an older one. `review_proposals` lists the open ones with both facts' text; read both,
  then `decide_proposal(event_id, apply|reject, reason)`.
  CURATION. Daily: `search_facts` for duplicates, stale or wrong facts, and junk (placeholder text
  like "..."). A duplicate or a corrected fact → `supersede_fact(old_id, new_id, reason)`; junk or a
  wrong fact nothing replaces → `forget_fact(fact_id, reason)`. Every change carries its reason.
  A fact about code with no check: name the command that would re-check it.
  LANDED WORKLINES. `landed_facts` lists the worklines landed since your last sweep with their
  facts. STATE that only mattered in flight ("X is at build on #N", "the branch has 2 commits",
  "QA passed on a036d4c", who was staffed) → `forget_fact` with the reason. A LESSON, decision or
  constraint about the code or the process → keep it. When unsure, keep.
  STATED FACTS are the operator's words and his always-loaded constraints: never supersede, forget
  or edit one — the tools refuse it. To change one, ask him: `ask_operator(question, options)`.
  QUESTIONS. A coworker asking "what do we know about X": answer from `search_facts`/`get_facts`
  (that cites what you used), with the fact ids, and say where the record is thin.
  WEEKLY. `knowledge_report(notes)` posts the counts in the lobby; your notes say what changed and
  what is shaky, three lines at most, with no @mention of the operator.#{@chat_etiquette}
  """

  # The researcher persona → `system_prompt.md`. The deep-research discipline, distilled.
  @researcher_role """
  You are {{handle}}, a deep RESEARCHER on this server task thread. Answer by fanning out
  across MULTIPLE independent sources, fetching the primary material, and reading it — not by
  recalling from memory. Verify every load-bearing claim adversarially: seek the source that would
  falsify it, and never state as fact what you could not confirm. Synthesize into a terse briefing
  with CITATIONS, and clearly separate what you VERIFIED from what a source merely ASSERTS. Post the
  synthesis to the thread. A confident answer built on an unchecked claim is the failure mode;
  distrust and cite.
  """

  # The assistant persona → `system_prompt.md`. A general life-assistant scoped to a non-code workspace.
  @assistant_role """
  You are {{handle}}, a capable general life-ASSISTANT for a non-code workspace (journal, notes,
  finances, and the like). Your substrate is the workspace's git-tracked files, scoped to its paths. Help
  the operator organize, summarize, retrieve, and draft across that material: keep notes tidy and
  cross-linked, surface what is relevant, and answer from what is actually written, not invention.
  Make small, reviewable edits and keep the history clean. Be warm but terse, and never touch paths
  outside the workspace you serve.
  """

  # The coworker-driver ring the SETTINGS panel cycles (leader `m`): the ollama models, each reached
  # through Claude Code's gateway (`Server.Harness.ClaudeCode`). `kimi-k3` stays out: ollama.com bills
  # it per token on top of the plan.
  @model_ring [
    %{provider: "ollama-cloud", model: "glm-5.2", thinking: "medium"},
    %{provider: "ollama-cloud", model: "kimi-k2.7-code", thinking: "medium"},
    %{provider: "ollama-cloud", model: "deepseek-v4-pro", thinking: "high"},
    %{provider: "ollama-cloud", model: "deepseek-v4.1-flash", thinking: "medium"},
    %{provider: "ollama-cloud", model: "glm-5.3", thinking: "medium"},
    %{provider: "ollama-cloud", model: "glm-5.3-flash", thinking: "medium"},
    %{provider: "ollama-cloud", model: "kimi-k2.6", thinking: "medium"},
    %{provider: "ollama-cloud", model: "minimax-m3", thinking: "medium"},
    %{provider: "ollama-cloud", model: "minimax-m2.7", thinking: "medium"}
  ]

  # Every archetype's default: real Claude. Not a model-ring entry; the operator retargets any
  # instance via the settings file (`Server.OperatorConfig`), a workspace policy or a roster entry.
  @sonnet %{provider: "anthropic", model: "claude-sonnet-5-5", thinking: "medium"}

  # The Claude models a coworker may be set to (`model_choices/0`), beside the ollama ring.
  @claude_choices [
    %{provider: "anthropic", model: "claude-opus-5-5", thinking: "medium"},
    @sonnet,
    %{provider: "anthropic", model: "claude-haiku-5-5", thinking: "medium"},
    %{provider: "anthropic", model: "claude-fable-5-1", thinking: "medium"}
  ]

  # The archetype registry — role TEMPLATES keyed by archetype atom. A template is the `%Profile{}`
  # content fields minus `name` (`model`/`mcp`/`sandbox`/`permissions`/`system_prompt`);
  # `instantiate/1` (Task 3) stamps an instance `name` over one to mint a materialisation-ready profile.
  # Each archetype is a distilled discipline — the "extract a superpower as a coworker" content.
  #   * surveyor  — the tertius meta/synthesis role (machine_overview cross-leaf read).
  #   * reviewer  — read-only code review; the write/edit deny-floor is STRUCTURAL (@reviewer_permissions).
  #   * builder   — TDD RED→GREEN→REFACTOR + verification-before-completion; can write.
  #   * planner   — writing-plans discipline (bite-sized TDD tasks, exact paths, DoD); can write.
  #   * sheriff   — owns red: triages every red signal on its beat, routes or fixes, escalates the real.
  #   * pm        — owns what ships: releasability, the release pointer, the changelog, backlog urgency; no writes.
  #   * qa        — drives a reviewed user-visible change on a scratch release and files what it saw; no writes.
  #   * librarian — owns the memory: decides the judge's proposals, supersedes/forgets with a reason; no writes.
  #   * researcher — deep multi-source fan-out + adversarial verification; sandbox scoped per workspace (tunable).
  #   * assistant — general life-assistant over a non-code workspace's git-tracked paths (sandbox tunable).
  @archetypes %{
    surveyor: %{
      model: @sonnet,
      mcp: @tertius_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @tertius_role
    },
    reviewer: %{
      model: @sonnet,
      mcp: @reviewer_mcp,
      sandbox: @tlon_sandbox,
      permissions: @reviewer_permissions,
      system_prompt: @reviewer_role
    },
    builder: %{
      model: @sonnet,
      mcp: @tlon_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @builder_role
    },
    planner: %{
      model: @sonnet,
      mcp: @tlon_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @planner_role
    },
    sheriff: %{
      model: @sonnet,
      mcp: @sheriff_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @sheriff_role
    },
    pm: %{
      model: @sonnet,
      mcp: @pm_mcp,
      sandbox: @tlon_sandbox,
      permissions: @reviewer_permissions,
      system_prompt: @pm_role
    },
    qa: %{
      model: @sonnet,
      mcp: @qa_mcp,
      sandbox: @tlon_sandbox,
      permissions: @reviewer_permissions,
      system_prompt: @qa_role
    },
    librarian: %{
      model: @sonnet,
      mcp: @librarian_mcp,
      sandbox: @tlon_sandbox,
      permissions: @reviewer_permissions,
      system_prompt: @librarian_role
    },
    # researcher/assistant: @tlon_sandbox is the STARTING point — Slice 1 scopes it to the workspace's
    # own paths (journal/notes vs the ficciones repo). Tunable, not final.
    researcher: %{
      model: @sonnet,
      mcp: @tlon_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @researcher_role
    },
    assistant: %{
      model: @sonnet,
      mcp: @tlon_mcp,
      sandbox: @tlon_sandbox,
      permissions: @tlon_permissions,
      system_prompt: @assistant_role
    }
  }

  # The seed roster — the name-keyed coworker instances, expressed as
  # `{archetype, name, model?}` roster ENTRIES (Slice 1's `workspace.roster[]` stores this exact shape).
  # `fetch/1`/`all/0`/`names/0` resolve these through `instantiate/1`, so the archetype registry is the
  # ONE content source — no more full `%Profile{}` structs duplicating the templates. Order is
  # significant (`names/0`): tertius first, then reviewer.
  #
  #   * tertius — the Tlön CENTER (Orbis Tertius meta agent `tertius`; its tmux socket is
  #     per Workspace, `Server.Tmux.socket/1` — not name-derived off this profile).
  #     NO model override — it inherits the surveyor archetype's default, leaving the settings file
  #     (`Server.OperatorConfig`) free to retarget it: a seed `model:` would be highest-precedence and shadow
  #     that override.
  #   * reviewer — the read-only review gate. NO model override → it inherits the reviewer archetype's
  #     Sonnet default.
  @seed_roster [
    %{archetype: :surveyor, name: "tertius"},
    %{archetype: :reviewer, name: "reviewer"}
  ]

  @doc """
  Look a profile up by name, or nil. Resolves the name to its seed roster ENTRY, then
  `instantiate/2` mints the `%Profile{}` from the archetype registry — so name-keyed `fetch` and
  the bench path share ONE content source.

  `workspace_id` folds in that workspace policy (`Server.Policy`: the model and the ask-vs-allow
  default the CONFIG pane writes), so it flows everywhere the profile does — the materialised
  settings.json AND the launcher flag — on the next coworker spawn. Without one the archetype
  default stands: a policy belongs to a PAIRING, so guessing a workspace would be worse than
  inheriting.
  """
  @spec fetch(String.t(), integer() | nil) :: Profile.t() | nil
  def fetch(name, workspace_id \\ nil) do
    with %{} = entry <- Enum.find(@seed_roster, &(&1.name == name)) do
      instantiate(entry, workspace_id)
    end
  end

  # The yolo knob rides inside the compiled permissions map, so an override only applies when the
  # archetype HAS a policy — the deny-floor stays compiled-in, never operator-editable. Operates on a
  # permissions map (what `instantiate/1` holds); a nil override or a profile without permissions is a
  # pass-through.
  defp apply_yolo_override(perms, nil), do: perms
  defp apply_yolo_override(perms, yolo), do: Map.put(perms, "yoloMode", yolo)

  @doc "Every registered coworker profile — the seed roster resolved through the archetype registry."
  @spec all() :: [Profile.t()]
  def all, do: Enum.map(@seed_roster, &instantiate/1)

  @doc "The names of the seed coworker profiles."
  @spec names() :: [String.t()]
  def names, do: Enum.map(@seed_roster, & &1.name)

  @doc "The model ring the settings verb cycles through, Claude-first."
  @spec model_ring() :: [map()]
  def model_ring, do: @model_ring

  @doc """
  Every model a coworker may be set to — the archetype defaults, then the ring, each once. The
  shell's office offers these when it hires or retargets a coworker.
  """
  @spec model_choices() :: [map()]
  def model_choices do
    @archetypes
    |> Map.values()
    |> Enum.map(& &1.model)
    |> Kernel.++(@claude_choices ++ @model_ring)
    |> Enum.uniq()
  end

  @doc "The archetype registry — a map of `archetype_atom => role template` (the Profile content minus a name)."
  @spec archetypes() :: %{atom() => map()}
  def archetypes, do: @archetypes

  @doc "The role template for one archetype atom (raises on an unknown key)."
  @spec archetype(atom()) :: map()
  def archetype(k), do: Map.fetch!(@archetypes, k)

  @doc """
  Build a materialisation-ready `%Profile{}` from a roster entry `%{archetype:, name:, model:, knobs:}`:
  identity (`name` → socket/config_dir/handle) is the instance name, content comes from the archetype
  template, and the system prompt is personalized with the instance handle. Model precedence:
  roster-entry `model` > the (workspace, coworker) policy's `model` (`Server.Workspaces.set_policy/3`)
  > the config's `coworkers.<name>` > the seat's grade (`OperatorConfig.grade_model/1`) > archetype
  default. The config and the grade apply to a seat, so a workspace-less fetch skips them.
  """
  @spec instantiate(%{required(:archetype) => atom(), required(:name) => String.t(), optional(any()) => any()}) ::
          Profile.t()
  def instantiate(%{archetype: key, name: name} = entry, workspace_id \\ nil) do
    t = archetype(key)
    policy = policy_for(workspace_id, name)
    model = entry[:model] || policy[:model] || policy[:configured] || policy[:graded] || t.model

    %Profile{
      name: name,
      archetype: key,
      workspace_id: workspace_id,
      harness: t[:harness] || :claude_code,
      mcp: t.mcp,
      model: model,
      sandbox: t.sandbox,
      permissions: apply_yolo_override(t.permissions, policy[:yolo]),
      system_prompt: personalize(t.system_prompt, name) <> lead_duties(workspace_id, name)
    }
  end

  # The (workspace, coworker) policy as a plain map, or `%{}` — the knobs this module folds in.
  # Workspace-less (a render preview with no space in hand) means no policy: the archetype default,
  # never another workspace's answer.
  defp policy_for(nil, _name), do: %{}

  defp policy_for(workspace_id, name) do
    workspace_id
    |> Server.Workspaces.bench_all()
    |> Enum.find(&(&1.name == name))
    |> case do
      %Server.Coworker{agent_id: agent_id, grade: grade} ->
        seat = %{configured: OperatorConfig.coworker_model(name), graded: OperatorConfig.grade_model(grade)}

        case Server.Workspaces.policy(workspace_id, agent_id) do
          %Server.Policy{} = p ->
            Map.merge(seat, %{model: p.model && atomize_model(p.model), yolo: yolo_of(p.ask_default)})

          nil ->
            seat
        end

      nil ->
        %{}
    end
  rescue
    _ -> %{}
  end

  defp yolo_of("allow"), do: true
  defp yolo_of("ask"), do: false
  defp yolo_of(_), do: nil

  # The policy's model round-trips as a JSON object; the profile wants the atom-keyed shape.
  defp atomize_model(%{"provider" => p, "model" => m} = j),
    do: %{provider: p, model: m, thinking: j["thinking"] || "medium"}

  defp atomize_model(%{provider: _} = m), do: m
  defp atomize_model(_), do: nil

  @doc """
  Normalize a `workspace.roster[]` entry to `instantiate/1`'s input shape `%{archetype: atom, name:
  string}`. Read tolerantly: server JSON (`%{"archetype" => "builder", "name" => "hronir"}`) or a
  test's atom-keyed map. An archetype STRING (the wire form) is resolved to the atom the registry
  is keyed by.
  """
  @spec roster_entry(map()) :: %{archetype: atom() | nil, name: String.t() | nil}
  def roster_entry(%Server.Coworker{} = seat), do: %{archetype: normalize_archetype(seat.archetype), name: seat.name}

  def roster_entry(entry) do
    %{
      archetype: normalize_archetype(entry["archetype"] || entry[:archetype]),
      name: entry["name"] || entry[:name]
    }
  end

  # Meta archetypes — the vantage/synthesis side (tertius). Never a leaf lead: excluded from
  # per-thread staffing and from the staffing default (per-thread-agents design, 2026-08-22).
  @meta_archetypes [:surveyor]

  @doc "Is this archetype a META role (vantage, never a leaf lead), as opposed to a WORKER?"
  @spec meta?(atom() | nil) :: boolean()
  def meta?(archetype), do: archetype in @meta_archetypes

  @doc """
  The server handles of a bench's WORKER (non-meta, registry-known) seats. Since the `-machine`
  suffix retired (UX slice 5) a handle IS the coworker's name — there is no transformation here,
  and that is the point.
  The set a thread lead is checked against to decide "does this leaf get its own per-thread
  session" (any harness — Slice A replaced the claude-only `claude_code_handles/1` gate).
  """
  @spec leaf_handles([map()]) :: [String.t()]
  def leaf_handles(roster) do
    roster
    |> Enum.map(&roster_entry/1)
    |> Enum.filter(fn %{archetype: a} -> a != nil and not meta?(a) end)
    |> Enum.map(fn %{name: n} -> n end)
  end

  @doc """
  The instantiated WORKER `%Profile{}` behind a leaf lead handle, resolved against `roster` — nil
  for a meta or bench-unknown lead (those get no per-thread session).
  `Server.Arbiter.Tmux` dispatches the leaf spawn on this profile's `harness`.
  """
  @spec leaf_profile(String.t(), [map()]) :: Profile.t() | nil
  def leaf_profile(handle, roster) do
    roster
    |> Enum.map(&roster_entry/1)
    |> Enum.find(fn %{archetype: a, name: n} -> a != nil and not meta?(a) and n == handle end)
    |> case do
      nil -> nil
      entry -> instantiate(entry)
    end
  end

  @doc """
  The instantiated `%Profile{}` behind any seat on `roster`, meta included — what a window opened
  for that coworker is launched with — on `workspace_id`'s bench, so the seat's own policy (its model,
  harness and grade) applies, not the archetype's default. nil for a handle with no registry-known seat.
  """
  @spec seat_profile(String.t(), [map()], integer()) :: Profile.t() | nil
  def seat_profile(handle, roster, workspace_id) do
    roster
    |> Enum.map(&roster_entry/1)
    |> Enum.find(fn %{archetype: a, name: n} -> a != nil and n == handle end)
    |> case do
      nil -> nil
      entry -> instantiate(entry, workspace_id)
    end
  end

  @doc """
  The model a seat actually runs, as one label for a commit trailer or a log — the launched profile's,
  never what a model says it is: `"ollama-cloud/kimi-k2.7-code (claude_code)"`, `"anthropic/claude-sonnet-5-5
  (claude_code)"`. nil for a name with no seat on the workspace.
  """
  @spec model_label(integer() | nil, String.t()) :: String.t() | nil
  def model_label(nil, _name), do: nil

  def model_label(workspace_id, name) do
    case seat_profile(name, Server.Workspaces.bench_all(workspace_id), workspace_id) do
      nil -> nil
      %Profile{model: model, harness: harness} -> "#{model_name(model)} (#{harness})"
    end
  end

  defp normalize_archetype(a) when is_atom(a), do: a

  # NOT `String.to_existing_atom/1`: that only succeeds once something has already loaded this
  # module (interning `:builder`/`:surveyor`/…) — an ordering accident. Resolving against the
  # compiled registry forces the load as an ordinary call, exhaustion-safe (a bounded set).
  defp normalize_archetype(a) when is_binary(a), do: Enum.find(Map.keys(@archetypes), &(Atom.to_string(&1) == a))

  # The handle IS the profile name (UX slice 5 retired the "-machine" suffix; the agent row, the
  # tmux window and the mention all spell it the same way now).
  # A prompt WITHOUT the {{handle}} placeholder (surveyor/reviewer) passes through
  # unchanged — String.replace is a no-op, so those personas stay byte-identical. Every
  # archetype carries a prompt (Elixir 1.20's type checker proved a nil clause dead).
  defp personalize(prompt, name), do: String.replace(prompt, "{{handle}}", name)

  # The workspace's lead (its first builder, `Server.Coworker.lead/1`) is its tech lead.
  defp lead_duties(nil, _name), do: ""

  defp lead_duties(workspace_id, name) do
    case Server.Workspaces.lead(workspace_id) do
      %{name: ^name} -> "\n\n" <> @tech_lead
      _ -> ""
    end
  end

  @doc "The ring entry after `current` (matched on provider+model), wrapping; unknown → the ring head."
  @spec next_model(map() | nil) :: map()
  def next_model(current) do
    i = Enum.find_index(@model_ring, &(&1.provider == current[:provider] and &1.model == current[:model]))

    case i do
      nil -> hd(@model_ring)
      i -> Enum.at(@model_ring, rem(i + 1, length(@model_ring)))
    end
  end

  @doc """
  Pure: profile → the files its config dir needs. `%{sandbox: map | nil, system_prompt: binary | nil}`.
  """
  @spec render(Profile.t()) :: %{sandbox: map() | nil, system_prompt: String.t() | nil}
  def render(%Profile{} = p), do: %{sandbox: p.sandbox, system_prompt: p.system_prompt}

  @doc """
  The ficciones repo root (matches flake.nix's `repo`) — coworkers/launchers outside this
  module that need a repo-relative path (e.g. the Tlön Claude-Code window) share this, not a
  second hardcoded copy.
  """
  @spec repo() :: String.t()
  def repo, do: @repo

  @doc """
  Where tlon's own checkout is — the release is built in place, so the source directory at compile
  time is the checkout. The launchers, adapters and `scripts/tlon-cli.sh` live here, not in `repo/0`.
  """
  @spec tlon_root() :: String.t()
  def tlon_root, do: Path.expand("../../..", __DIR__)

  @doc """
  The config dir a profile materialises into, keyed by workspace so
  two workspaces can run the same coworker name under different policy. A workspace-less profile
  keeps the flat path.
  """
  @spec config_dir(Profile.t()) :: String.t()
  def config_dir(profile) do
    case profile do
      %Profile{workspace_id: nil, name: n} -> Path.join(profiles_root(), n)
      %Profile{workspace_id: id, name: n} -> Path.join([profiles_root(), "w#{id}", n])
    end
  end

  @doc "The persistence-free tmux config a coworker's server boots from (see `@coworker_tmux_conf`)."
  @spec tmux_conf() :: String.t()
  def tmux_conf, do: @coworker_tmux_conf

  @doc """
  Materialise a profile's config dir: its persona, its sandbox and the tmux config its workspace's
  server boots from. Idempotent — re-materialised on every spawn, so editing a profile + respawning
  the coworker is the whole loop. Returns the dir.

  `opts[:root]` overrides the profiles root (for tests).
  """
  @spec materialise!(Profile.t(), keyword()) :: String.t()
  def materialise!(%Profile{} = p, opts \\ []) do
    # The dir MUST be `config_dir/1`: the launcher reads the persona and sandbox from that path.
    dir = if opts[:root], do: Path.join(opts[:root], p.name), else: config_dir(p)
    File.mkdir_p!(dir)
    r = render(p)
    if r.sandbox, do: write_json!(Path.join(dir, "sandbox.json"), r.sandbox)
    if r.system_prompt, do: File.write!(Path.join(dir, "system_prompt.md"), r.system_prompt)
    File.write!(Path.join(dir, "tmux.conf"), @coworker_tmux_conf)
    dir
  end

  defp profiles_root do
    state = System.get_env("XDG_STATE_HOME") || Path.expand("~/.local/state")
    Path.join([state, "tlon", "profiles"])
  end

  defp write_json!(path, map), do: File.write!(path, Jason.encode!(map, pretty: true) <> "\n")

  defp model_name(%{provider: provider, model: model}), do: "#{provider}/#{model}"
  defp model_name(model) when is_binary(model), do: model
  defp model_name(model), do: inspect(model)
end
