#!/usr/bin/env bash
# Write the generated task manual (docs/manual/tasks.md) from `mise tasks ls`.
# `--check` only diffs, exit 1 on drift — `mise run manual:check`. A generated page is never
# edited by hand.
set -euo pipefail
cd "$(dirname "$0")/.."
mode="${1:-write}"
out="$(mktemp -d)"
trap 'rm -rf "$out"' EXIT

# ---- tasks.md: every mise verb, by group -------------------------------------------------------
mise tasks ls --json > "$out/tasks.json"
python3 - "$out/tasks.json" > "$out/tasks.md" <<'PY'
import json, sys
tasks = json.load(open(sys.argv[1]))
groups = {}
for t in tasks:
    g = t["name"].split(":")[0] if ":" in t["name"] else "—"
    groups.setdefault(g, []).append(t)
print("# Verbs\n")
print("Every verb is `mise run <name>`; the same loop for the human and the agents (AGENTS.md). Generated by `mise run manual:gen` from `mise tasks ls --json` — a verb is defined in `tasks/<group>.toml`, never here.\n")
print(f"{len(tasks)} verbs in {len(groups)} groups.\n")
for g in sorted(groups):
    print(f"## {g}\n\n| verb | does |\n|---|---|")
    for t in sorted(groups[g], key=lambda t: t["name"]):
        d = (t.get("description") or "").replace("|", "\\|").replace("\n", " ")
        print(f"| `{t['name']}` | {d} |")
    print()
PY

rc=0
for f in tasks; do
  dst="docs/manual/$f.md"
  if [ "$mode" = "--check" ]; then
    if ! diff -u "$dst" "$out/$f.md" >/dev/null 2>&1; then echo "manual:check — $dst drifts from its source (run: mise run manual:gen)"; rc=1; fi
  else
    cp "$out/$f.md" "$dst"; echo "manual:gen — wrote $dst"
  fi
done
exit $rc
