#!/usr/bin/env bash
# Write the generated manual pages (docs/manual/{keys,tasks,palette}.md) from their sources.
# `--check` only diffs, exit 1 on drift — `mise run manual:check`. Same rule as theme-gen.sh:
# a page with a source is never edited by hand.
set -euo pipefail
cd "$(dirname "$0")/.."
mode="${1:-write}"
out="$(mktemp -d)"
trap 'rm -rf "$out"' EXIT

# ---- keys.md: the bind(...) lines of hyprland.lua --------------------------------------------
# hyprctl binds -j only knows a Lua bind as `__lua <n>`, so the SOURCE is the record. Best-effort
# parse: the first argument is the keys (M = SUPER), the second the action; a trailing `--`
# comment, when present, is the human line.
python3 - modules/desktop/hypr/hyprland.lua > "$out/keys.md" <<'PY'
import re, sys
src = open(sys.argv[1], encoding="utf-8").read().splitlines()
mod = re.search(r'^local M = "(\w+)"', "\n".join(src), re.M)
M = mod.group(1) if mod else "SUPER"
rows = []
for line in src:
    m = re.match(r'^\s*bind\((.*)\)\s*(?:--\s*(.*))?$', line)
    if not m: continue
    inner, comment = m.group(1), (m.group(2) or "").strip()
    # keys = everything up to the first top-level comma
    depth, cut = 0, None
    for i, ch in enumerate(inner):
        if ch in "([{": depth += 1
        elif ch in ")]}": depth -= 1
        elif ch == "," and depth == 0: cut = i; break
    if cut is None: continue
    keys_expr, action = inner[:cut], inner[cut+1:].strip()
    keys = keys_expr.replace("M", M).replace("..", "").replace('"', "").strip()
    keys = re.sub(r"\s*\+\s*", "+", keys)
    mouse = "{ mouse = true }" in action
    action = re.sub(r",\s*\{\s*mouse = true\s*\}\s*$", "", action).strip()
    def group(a):
        if a.startswith("exec("): return "launch"
        if a.startswith(("ws(", "to_ws(", "follow_ws(")): return "workspaces"
        if a.startswith(("move(", "move_mon(", "resize(")) or "colresize" in a or "sidecar" in a: return "move & size"
        if a.startswith("layout("): return "layout"
        if a.startswith("hl.dsp.focus"): return "focus"
        if a.startswith("hl.dsp.window") or a.startswith("unless_pinned("): return "window"
        return "other"
    def what(a, c):
        if c: return c
        e = re.match(r'exec\((.*)\)$', a)
        if e:
            arg = e.group(1).strip().strip('"')
            arg = re.sub(r'^shell \.\. "/', "shell/", arg).strip('"')
            return "`" + arg[:60] + "`"
        return "`" + a[:60] + "`"
    rows.append(("mouse" if mouse else group(action), keys, what(action, comment)))
order = ["launch", "focus", "move & size", "layout", "workspaces", "window", "mouse", "other"]
print("# Keys\n")
print("Generated from `modules/desktop/hypr/hyprland.lua` by `mise run manual:gen` — edit THAT, never this file.")
print(f"{len(rows)} binds. `{M}` is the main modifier. The shell draws the live sheet too (`astal-shell toggle cheatsheet`, bound under launch).\n")
for g in order:
    mine = [r for r in rows if r[0] == g]
    if not mine: continue
    print(f"## {g}\n\n| keys | does |\n|---|---|")
    for _, k, w in mine: print(f"| `{k}` | {w} |")
    print()
PY

# ---- tasks.md: every mise verb, by group -------------------------------------------------------
mise tasks ls --json > "$out/tasks.json"
python3 - "$out/tasks.json" > "$out/tasks.md" <<'PY'
import json, sys
tasks = json.load(open(sys.argv[1]))
groups = {}
for t in tasks:
    g = t["name"].split(":")[0] if ":" in t["name"] else "—"
    groups.setdefault(g, []).append(t)
print("# Verbs\n")
print("Every verb is `mise run <name>`; the same loop for the human and the agents (AGENTS.md). Generated by `mise run manual:gen` from `mise tasks ls --json` — a verb is defined in `tasks/<group>.toml`, never here.\n")
print(f"{len(tasks)} verbs in {len(groups)} groups. The launcher lists them under `>`.\n")
for g in sorted(groups):
    print(f"## {g}\n\n| verb | does |\n|---|---|")
    for t in sorted(groups[g], key=lambda t: t["name"]):
        d = (t.get("description") or "").replace("|", "\\|").replace("\n", " ")
        print(f"| `{t['name']}` | {d} |")
    print()
PY

# ---- palette.md: the roles, both palettes -------------------------------------------------------
roles="$(nix eval --json --impure --expr '
  let u = import ./modules/desktop/theme/palettes/uqbar.nix; z = import ./modules/desktop/theme/palettes/zahir.nix;
  in { uqbar = u.role; zahir = z.role; font = u.font; }')"
python3 - "$roles" > "$out/palette.md" <<'PY'
import json, sys
p = json.loads(sys.argv[1])
print("# Palette\n")
print("Generated by `mise run manual:gen` from `modules/desktop/theme/palettes/{uqbar,zahir}.nix` — the palette is data there; every surface (shell, console, ghostty, GTK/Qt, btop, floorp, hyprlock, lazygit, bat, fzf, cava, tmux, Claude Code, Neovim) is rendered from it by `render.nix`. Nothing else on the machine carries a hex value.\n")
print(f"Font: **{p['font']['family']}** everywhere, {p['font']['size']}pt base (low vision: sizes bias up, never down).\n")
print("## The law\n")
print("- **Body text is amber on black** (uqbar) — dark amber on cream in zahir. Cyan = keys, labels, code, links. Lilac = secondary text.")
print("- **Amber field = the CURSOR** (where you are: focused workspace, active tab, list row) as inverse video. **Violet field = the SELECTION** (what you picked and left behind). The test: *if you look away, does it stay?*")
print("- Green = live/occupied. Pink = agents, the operator, attention. Red = alarm. Ember = warning, one step before red.")
print("- Every pair clears WCAG AAA (7:1 text, 3:1 bands) in BOTH palettes — `mise run theme:contrast` proves it.\n")
print("## Roles\n\n| role | uqbar | zahir |\n|---|---|---|")
for k in sorted(p["uqbar"]):
    print(f"| `{k}` | `#{p['uqbar'][k]}` | `#{p['zahir'].get(k, '—')}` |")
print()
print("Surfaces name a ROLE, never a hue — `render.nix` cannot reach `p.hue`. Syntax colouring in Neovim is a CATEGORY tier (base16 slots bound in `render.nix`), the one place hues are bound for code.")
PY

rc=0
for f in keys tasks palette; do
  dst="docs/manual/$f.md"
  if [ "$mode" = "--check" ]; then
    if ! diff -u "$dst" "$out/$f.md" >/dev/null 2>&1; then echo "manual:check — $dst drifts from its source (run: mise run manual:gen)"; rc=1; fi
  else
    cp "$out/$f.md" "$dst"; echo "manual:gen — wrote $dst"
  fi
done
exit $rc
