defmodule Console.Icons do
  @moduledoc """
  The app-wide icon hub, two tiers.

  * **Raster (kitty):** a Lucide (https://lucide.dev, ISC) PNG, placed over a cell rect via the kitty
    graphics protocol (`Console.Graphics` / `Panel.images/2`). Kitty scales the PNG to the placement,
    so one generously-rendered image works at any font size. The PNGs are generated by
    `priv/icons/generate.sh` and **embedded at compile time** (no runtime file IO).
  * **Glyph (fallback):** a Nerd Font (https://www.nerdfonts.com) codepoint, rendered as a normal
    cell. This is what shows when the host isn't kitty-capable (`Graphics.kitty?/0` false), or for
    inline spots too small/awkward for an image (border titles, chips). A bare BMP symbol like `⌂` is
    NOT safe (it tofu'd on ghostty even though the Nerd PUA range renders), so glyphs come from here.

  Add an icon: add a `name:lucide-name` row to `generate.sh`, re-run it, add the `name => codepoint`
  glyph below, and reference `Icons.name/0` (glyph) or `Icons.image(:name, rect)` (raster).
  """

  @dir Path.join([__DIR__, "..", "..", "priv", "icons"])

  # name => Nerd Font codepoint (the glyph fallback). The Lucide PNG of the same name is the raster
  # tier. Keep to well-supported Font Awesome (`nf-fa-*`) codepoints.
  @glyphs %{
    home: "\u{F015}",
    add: "\u{F067}",
    settings: "\u{F013}",
    ticket: "\u{F02B}",
    note: "\u{F249}",
    now: "\u{F0E7}",
    crew: "\u{F0C0}",
    memory: "\u{F2DB}",
    stack: "\u{F126}",
    threads: "\u{F086}",
    # Workspace DISPLAY icons — the choices in the right-click "Set icon…" picker (a workspace's
    # `knobs["icon"]` names one). Kitty-only (a workspace with no icon falls back to its digit).
    rocket: "\u{F135}",
    box: "\u{F466}",
    folder: "\u{F07B}",
    code: "\u{F121}",
    terminal: "\u{F120}",
    globe: "\u{F0AC}",
    star: "\u{F005}",
    layers: "\u{F5FD}",
    flask: "\u{F0C3}",
    cpu: "\u{F2DB}",
    # Workspace digit icons (`d1`…`d9`): the fallback glyph is just the digit char; the raster tier is
    # a matching thin-sans PNG so a numbered workspace reads as an icon, not terminal text.
    d1: "1",
    d2: "2",
    d3: "3",
    d4: "4",
    d5: "5",
    d6: "6",
    d7: "7",
    d8: "8",
    d9: "9"
  }

  @names Map.keys(@glyphs)

  @doc "The digit icon name for a 1-based workspace position (`1` → `:d1`), or nil past 9."
  @spec digit(pos_integer()) :: atom() | nil
  def digit(n) when n in 1..9, do: :"d#{n}"
  def digit(_n), do: nil

  # The choices in the workspace "Set icon…" picker, in display order.
  @workspace_icons ~w(rocket box folder code terminal globe star layers flask cpu)a

  @doc "The workspace display-icon choices (the Set-icon picker), in order."
  @spec workspace_icons() :: [atom()]
  def workspace_icons, do: @workspace_icons

  @doc "Coerce a stored `knobs[\"icon\"]` value to a known icon name atom, or nil."
  @spec icon_name(term()) :: atom() | nil
  def icon_name(name) when is_atom(name), do: if(name in @workspace_icons, do: name)
  def icon_name(name) when is_binary(name), do: Enum.find(@workspace_icons, &(to_string(&1) == name))
  def icon_name(_name), do: nil

  # Recompile if a PNG changes; embed the bytes so there's no per-frame file IO.
  for name <- @names, do: @external_resource Path.join(@dir, "#{name}.png")
  @pngs (for name <- @names, into: %{}, do: {name, File.read!(Path.join(@dir, "#{name}.png"))})

  # A stable kitty image id per icon (transmit-once cache key). 7000+ keeps clear of any ad-hoc ids a
  # panel might use for its own imagery.
  @ids (for {name, i} <- Enum.with_index(@names, 7000), into: %{}, do: {name, i})

  @doc "Every icon name."
  @spec names() :: [atom()]
  def names, do: @names

  @doc "The Nerd Font glyph for `name` (the fallback tier), or nil."
  @spec glyph(atom()) :: String.t() | nil
  def glyph(name), do: Map.get(@glyphs, name)

  @doc """
  A kitty image placement for `name` over `rect` — `%{id, data, rect}` for `Console.Graphics.sync/2`
  (what a panel returns from `images/2`), or nil for an unknown name. The caller places the glyph in
  the cell too; on kitty the image overpaints it, off kitty the glyph shows.
  """
  @spec image(atom(), map()) :: map() | nil
  def image(name, rect) do
    case Map.get(@pngs, name) do
      nil -> nil
      png -> %{id: Map.fetch!(@ids, name), data: png, rect: rect}
    end
  end

  # Named glyph accessors — the inline callers (`Icons.home()`), kept stable so a codepoint swap is
  # one line above and every call site follows.
  for name <- @names do
    @doc "The `#{name}` glyph (Nerd Font fallback tier)."
    def unquote(name)(), do: @glyphs[unquote(name)]
  end
end
